server.port=8080

spring.profiles.active=dev

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.servlet.multipart.file-size-threshold=10MB

spring.mail.host=smtp.naver.com
spring.mail.port=587
spring.mail.username=${mail.username}
spring.mail.password=${mail.password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/daall_coffee?characterEncoding=UTF-8
spring.datasource.username=${db.username}
spring.datasource.password=${db.password}
spring.datasource.type=org.apache.commons.dbcp2.BasicDataSource
spring.datasource.dbcp2.initial-size=0
spring.datasource.dbcp2.min-idle=2
spring.datasource.dbcp2.max-idle=30
spring.datasource.dbcp2.max-total=30
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT
JWT_KEY=${SECRET_JWT_KEY}
JWT_ACCESS_EXPIRATION=1800000
JWT_REFRESH_EXPIRATION=604800000

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

logging.level.java.io.serialization=INFO
logging.level.javax.management=INFO
logging.level.sun.rmi=INFO
logging.level.org.apache.tomcat.util.net=INFO
logging.level.org.apache.coyote=INFO
logging.level.org.apache.jasper=INFO
logging.level.org.apache.catalina.loader=INFO

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.core.env=DEBUG
logging.level.org.daCoffee=DEBUG
server.error.whitelabel.enabled=false

spring.config.import=optional:classpath:/config/secrets.properties

COOKIE_LOGIN=${SECRET_COOKIE_LOGIN}
ADMIN_ID=${SECRET_ADMIN_ID}
TOSS_CUSTOMER_KEY=${SECRET_TOSS_CUSTOMER_KEY}
TOSS_WIDGET_SECRET_KEY=${SECRET_TOSS_WIDGET_KEY}

DELIVERY_FEE=3000

FILE_UPLOAD_PATH=${file.upload.path:C:/data/dacoffee/files}